<a href="https://colab.research.google.com/github/yenlensarnaan/DTS-103/blob/main/WEEK_6_Pandas_for_Data_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


# 📘 ASSIGNMENT (Week 6)

Using Pandas:

1. Create a new CSV file with at least 10 students.
2. Load the CSV using pd.read_csv().
3. Compute:
   - Subject averages
   - Overall student averages
4. Identify:
   - Top performing student
   - Lowest performing student
5. Export the updated dataset to a new CSV file.

Submit your completed notebook (.ipynb).

In [ ]:

import pandas as pd

In [ ]:

data = {
    "Name": ["Joshua", "Michael", "Peter", "Joel", "Enoch", "Godwin", "Samson", "Faith", "Joy", "Happiness"],
    "History": [85, 63, 56, 48, 90, 69, 56, 77, 59, 45],
    "Economics": [75, 90, 85, 56, 45, 38, 73, 59, 82, 60],
    "French": [90, 65, 78, 59, 60, 45, 55, 71, 69, 85]
}

df = pd.DataFrame(data)

df.to_csv("students.csv",index = False)
df

        Name  History  Economics  French
0     Joshua       85         75      90
1    Michael       63         90      65
2      Peter       56         85      78
3       Joel       48         56      59
4      Enoch       90         45      60
5     Godwin       69         38      45
6     Samson       56         73      55
7      Faith       77         59      71
8        Joy       59         82      69
9  Happiness       45         60      85

In [ ]:
import pandas as pd

df = pd.read_csv("students.csv")
df

        Name  History  Economics  French
0     Joshua       85         75      90
1    Michael       63         90      65
2      Peter       56         85      78
3       Joel       48         56      59
4      Enoch       90         45      60
5     Godwin       69         38      45
6     Samson       56         73      55
7      Faith       77         59      71
8        Joy       59         82      69
9  Happiness       45         60      85

In [44]:

df["Average"] = df[["History", "Economics", "French"]].mean(axis=1)
df

        Name  History  Economics  French    Average
0     Joshua       85         75      90  83.333333
1    Michael       63         90      65  72.666667
2      Peter       56         85      78  73.000000
3       Joel       48         56      59  54.333333
4      Enoch       90         45      60  65.000000
5     Godwin       69         38      45  50.666667
6     Samson       56         73      55  61.333333
7      Faith       77         59      71  69.000000
8        Joy       59         82      69  70.000000
9  Happiness       45         60      85  63.333333

In [49]:

df[["History", "Economics", "French"]].mean()

History      64.8
Economics    66.3
French       67.7
dtype: float64

In [50]:

df.max()

Name            Samson
History             90
Economics           90
French              90
Average      83.333333
dtype: object

In [51]:

df.min()

Name             Enoch
History             45
Economics           38
French              45
Average      50.666667
dtype: object

Name: Yenle Nsarnaan Istifanus
Mat No: UJ/2025/CP/0257
Programme:Data science
Department: Computer science
Assignment: week4